Реализован график PieChart
Otus-Android/HomeWork_07 pull request #35
Opened 2022-08-31 10:52 UTC by yeliseyL

2022-09-03 12:56 UTC, antonkazakov commented
Привет. По отрисовке все ок, но нет механизма сохранения/восстановления состояния

2022-09-03 12:57 UTC, antonkazakov requested changes

2022-09-03 12:57 UTC, antonkazakov commented on app/src/main/java/otus/homework/customview/GraphView.kt
> +            color = Color.BLUE
Примени еще к Paint флаг ANTI_ALIASING, чтобы не было артефактов при рисовании наклонных линий

2022-09-04 16:31 UTC, yeliseyL commented on app/src/main/java/otus/homework/customview/GraphView.kt
> +            color = Color.BLUE
Применил

2022-09-04 16:32 UTC, yeliseyL commented
> 



> Привет. По отрисовке все ок, но нет механизма сохранения/восстановления состояния

Добавил

2022-09-18 15:49 UTC, antonkazakov commented
👍

2022-09-18 15:49 UTC, closed without merging